### ISSUE TITLE
flag provided but not defined: -C

### ISSUE THREAD

**Issue by Kotsuha** [nnn-revo2012/livedl-n#2]
Hello. I have an old version of livedl

```
λ livedl --version
livedl (20210228.48-windows-386)
```

Recently I tried to use it to download a TS on niconico. It's not working anymore. I then go to the author's GitHub and then I found this one. I tried to build but failed.

```
C:\tmp
λ git clone "https://github.com/nnn-revo2012/livedl-n.git"
Cloning into 'livedl-n'...
remote: Enumerating objects: 1377, done.
remote: Counting objects: 100% (1377/1377), done.
remote: Compressing objects: 100% (443/443), done.
remote: Total 1377 (delta 811), reused 1337 (delta 771), pack-reused 0 (from 0)
Receiving objects: 100% (1377/1377), 369.99 KiB | 2.52 MiB/s, done.
Resolving deltas: 100% (811/811), done.

C:\tmp
λ cd livedl-n\

C:\tmp\livedl-n (master -> origin)
λ dir
 Volume in drive C is Windows
 Volume Serial Number is D8AE-7AED

 Directory of C:\tmp\livedl-n

12/30/2024  12:33 AM    <DIR>          .
12/30/2024  12:33 AM    <DIR>          ..
12/30/2024  12:33 AM               229 .gitignore
12/30/2024  12:33 AM               268 build-386.ps1
12/30/2024  12:33 AM             7,059 BUILD.md
12/30/2024  12:33 AM             1,451 build.ps1
12/30/2024  12:33 AM            15,041 changelog.txt
12/30/2024  12:33 AM               403 Dockerfile
12/30/2024  12:33 AM             1,115 LICENSE
12/30/2024  12:33 AM               486 readme-gen.pl
12/30/2024  12:33 AM             1,985 README.md
12/30/2024  12:33 AM            21,964 README.txt
12/30/2024  12:33 AM               931 replacelocal.pl
12/30/2024  12:33 AM    <DIR>          src
              11 File(s)         50,932 bytes
               3 Dir(s)  214,612,742,144 bytes free

C:\tmp\livedl-n (master -> origin)
λ go build -C src -o ../livedl.exe livedl.go
flag provided but not defined: -C
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.

C:\tmp\livedl-n (master -> origin)
λ go version
go version go1.19.2 windows/amd64

```

**Comment by nnn-revo2012** [comment]
If you want to use livedl-n on Windows, use the pre-built binaries available at the link below,
or upgrade Go to version 1.20.x or later and build it yourself.

https://github.com/nnn-revo2012/livedl-n/releases/tag/20241221.56

In the future, Nicolive videos will be encrypted, so I will no longer be able to create a video download feature to avoid violating Japanese copyright laws.
If you don't need the Danmaku(comments), I recommend using yt-dlp or Streamlink, as they do not violate Japanese copyright laws.

**Comment by nnn-revo2012** [comment]
Niconico was hacked by hackers in June 2024, leading to a suspension of services. The platform resumed operations in August, but as a result, security measures have been enhanced, and access from overseas is now restricted.

Additionally, if you have not logged in since August, you will need to reset your password through your browser.

Apologies for the Japanese text. Please read the translated version.
https://blog.nicovideo.jp/niconews/225255.html

**Comment by Kotsuha** [comment]
> If you want to use livedl-n on Windows, use the pre-built binaries available at the link below,

Thank you. I've downloaded the pre-built binary and used it. I don't know why, it cannot download the full TS completely. This is a part of the log:

```
E:\_\Live\20241220｜ニコ lv345989786｜【Day1】にじさんじ歌謡祭2024
λ livedl --version
chdir: C:\PortableApps (CLI)\livedl-n
livedl (20241221.56-windows-amd64)

E:\_\Live\20241220｜ニコ lv345989786｜【Day1】にじさんじ歌謡祭2024
λ livedl -no-chdir -nico-login-only=on -nico-login "xxx@yyy.com,zzz" "lv345989786"
no chdir
read E:\_\Live\20241220｜ニコ lv345989786｜【Day1】にじさんじ歌謡祭2024\conf.db
niconico account saved.
Conf(NicoLoginOnly): true
Conf(NicoFormat): ""
Conf(NicoLimitBw): "0"
Conf(NicoFastTs): false
Conf(NicoAutoConvert): false
Conf(NicoForceResv): false
Conf(NicoSkipHb): false
Conf(NicoAdjustVpos): false
Conf(HttpSkipVerify): false
Conf(HttpTimeout): 5
account: premium
providertype: official
2024/12/31 22:38:56 connect messageServer at: 1734698785
2024/12/31 22:38:56 connect packedServer
2024/12/31 22:38:57 connect packedServer
BANDWIDTH: 10800000
2024/12/31 22:38:58 connect packedServer
Current SeqNo: 0, Pos: 00:00
2024/12/31 22:38:58 connect packedServer
2024/12/31 22:38:59 connect packedServer
2024/12/31 22:39:00 connect packedServer
2024/12/31 22:39:01 connect packedServer
2024/12/31 22:39:02 connect packedServer
Current SeqNo: 0, Pos: 00:00
2024/12/31 22:39:03 connect packedServer
2024/12/31 22:39:05 connect packedServer
2024/12/31 22:39:06 connect packedServer
2024/12/31 22:39:07 connect packedServer
2024/12/31 22:39:08 connect packedServer
Current SeqNo: 0, Pos: 00:00
2024/12/31 22:39:09 connect packedServer
2024/12/31 22:39:11 connect packedServer
2024/12/31 22:39:12 connect packedServer
Current SeqNo: 1, Pos: 00:05
2024/12/31 22:39:14 connect packedServer
2024/12/31 22:39:16 connect packedServer
2024/12/31 22:39:17 connect packedServer
Current SeqNo: 2, Pos: 00:10
2024/12/31 22:39:19 connect packedServer
2024/12/31 22:39:21 connect packedServer
2024/12/31 22:39:23 connect packedServer
Current SeqNo: 3, Pos: 00:15
2024/12/31 22:39:25 connect packedServer
2024/12/31 22:39:27 connect packedServer
Current SeqNo: 4, Pos: 00:20
2024/12/31 22:39:29 connect packedServer
2024/12/31 22:39:31 connect packedServer
2024/12/31 22:39:33 connect packedServer

(略)

Current SeqNo: 21, Pos: 01:45
2024/12/31 22:40:55 connect packedServer
2024/12/31 22:40:58 connect packedServer
Current SeqNo: 22, Pos: 01:50
2024/12/31 22:41:02 connect packedServer
2024/12/31 22:41:05 playlist: <nil>
2024/12/31 22:41:05 websocket read: read tcp 192.168.1.108:11014->13.35.7.95:443: use of closed network connection
2024/12/31 22:41:05 disconnect packedSegment server.
2024/12/31 22:41:05 connect packedServer
2024/12/31 22:41:05 packedServer connect error: Get "https://mpn.live.nicovideo.jp/data/backward/v4/BBy-rASmWwXXTIYHocu0jVIUfPy5FFdLgpHQWh2FHyk7sWOSUzz7oLD8wfGjaeYRssiY45cdX5Y8kuZK2v8": context canceled
2024/12/31 22:41:05 disconnect packedSegment server.
2024/12/31 22:41:06 connect messageServer at: 1734698785
2024/12/31 22:41:06 connect packedServer
2024/12/31 22:41:07 connect packedServer
BANDWIDTH: 10800000
2024/12/31 22:41:07 connect packedServer
Current SeqNo: 27, Pos: 02:15
2024/12/31 22:41:08 connect packedServer
2024/12/31 22:41:09 connect packedServer
2024/12/31 22:41:10 connect packedServer
2024/12/31 22:41:11 connect packedServer
2024/12/31 22:41:11 connect packedServer
2024/12/31 22:41:12 connect packedServer
Current SeqNo: 27, Pos: 02:15
2024/12/31 22:41:13 connect packedServer
2024/12/31 22:41:15 connect packedServer
2024/12/31 22:41:16 connect packedServer
2024/12/31 22:41:17 connect packedServer

(略)

Current SeqNo: 145, Pos: 12:05
2024/12/31 22:51:09 connect packedServer
2024/12/31 22:51:13 connect packedServer
2024/12/31 22:51:13 playlist: <nil>
2024/12/31 22:51:13 disconnect packedSegment server.
2024/12/31 22:51:13 websocket read: read tcp 192.168.1.108:11094->13.35.7.65:443: use of closed network connection
panic: send on closed channel

goroutine 6433255 [running]:
github.com/nnn-revo2012/livedl/niconico.(*PackedSegment).Connect(0xc000a1e3c0)
        github.com/nnn-revo2012/livedl/niconico/nico_packed.go:121 +0x63e
github.com/nnn-revo2012/livedl/niconico.(*NicoHls).ConnectPackedServer.func1.2(0xc000bb28a0?)
        github.com/nnn-revo2012/livedl/niconico/nico_hls.go:1202 +0x65
github.com/nnn-revo2012/livedl/gorman.(*GoroutineManager).Go.func1()
        github.com/nnn-revo2012/livedl/gorman/gorman.go:58 +0x73
created by github.com/nnn-revo2012/livedl/gorman.(*GoroutineManager).Go
        github.com/nnn-revo2012/livedl/gorman/gorman.go:56 +0xca

E:\_\Live\20241220｜ニコ lv345989786｜【Day1】にじさんじ歌謡祭2024
λ
```

I tried four times, each time it stopped at different location. The full TS is around 4 hours long.

Try | Downloaded Video Length
--- | -----------------------
1st | 00:34:50
2nd | 01:17:14
3rd | 00:55:09
4th | 00:12:29

Do you know why? Thank you.

P.S. Happy new year!

**Comment by nnn-revo2012** [comment]
I think the connection is timing out due to the end-of-year congestion in Japan and access from overseas.  
If you change the timeout to around 45 seconds, I believe you’ll be able to retrieve all the comments.  
(From Japan, it takes about 20 minutes to retrieve all the comments.)  

```  
livedl -http-timeout 45  
```  

If you encounter an error while fetching the video, please use yt-dlp or Streamlink to download just the video.

**Comment by Kotsuha** [comment]
Both `livedl -http-timeout 45` and yt-dlp worked for me. Thank you.

Q1:
Does livedl have an option to download just the comments?

Q2:
> In the future, Nicolive videos will be encrypted

Do you know about when this will happen?

Q3:
> In the future, Nicolive videos will be encrypted

When this happens, can I still use livedl to download the comments? Or do you have other recommendation?

Sorry for lots of questions.

**Comment by nnn-revo2012** [comment]
> Q1:
> Does livedl have an option to download just the comments?

Nothing
In the near future, it will likely become a comment-only download.

> Q2:
> Do you know about when this will happen?

About March 2025
Sorry for japanese.
https://blog.nicovideo.jp/niconews/235926.html

> Q3:
> When this happens, can I still use livedl to download the comments? Or do you have other 
> recommendation?

The tool created by Japanese developers is likely to be a comment download-only tool.
example　ニコ生録画ツール（仮、 livedl-n(my tool)

**Comment by Kotsuha** [comment]
Thanks for detailed answer. you've helped me so much.
